Tecton: t1
Type: normal
Mushroom: m1
Insects: insect1
Yarns: y1
Neighbours: t2
Spores: none

Tecton: t2
Type: normal
Mushroom: none
Insects: none
Yarns: y1
Neighbours: t1
Spores: none

Mushroom: m1
HasSpore: false
Place: t1
Owner: Bob

Insect: insect1
Current Effect: none
Owner: Alice

Yarn: y1
Type: killerYarn
Tectons in yarn: t1 t2

Player: Bob
Type: MushroomPicker
Points: 0

Player: Alice
Type: Entomologist
Points: 0

