Tecton: t1
Type: normal
Mushroom: m1
Insects: none
Yarns: y1
Neighbours: t2
Spores: none

Tecton: t2
Type: normal
Mushroom: none
Insects: none
Yarns: none
Neighbours: t1 t3
Spores: none

Tecton: t3
Type: normal
Mushroom: none
Insects: none
Yarns: none
Neighbours: t2
Spores: none

Mushroom: m1
HasSpore: false
Place: t1
Owner: Bob

Yarn: y1
Type: normal
Tectons in yarn: t1

Player: Bob
Type: MushroomPicker
Points: 0

